In [184]:
import tensorflow as tf
from tensorflow import keras

In [185]:
tf.constant([[1.,2,3], [4,5,6]])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [186]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [187]:
t = tf.constant([[1.,2,3],[4,5,6]])
t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [188]:
t.shape

TensorShape([2, 3])

In [189]:
t.dtype

tf.float32

In [190]:
t[:, 1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [191]:
t[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [192]:
t[..., tf.newaxis, 2]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[3.],
       [6.]], dtype=float32)>

In [193]:
t[..., 2, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[3.],
       [6.]], dtype=float32)>

In [194]:
t[1, tf.newaxis]

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[4., 5., 6.]], dtype=float32)>

In [195]:
t[tf.newaxis, 1]

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[4., 5., 6.]], dtype=float32)>

In [196]:
t+10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [197]:
t*10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[10., 20., 30.],
       [40., 50., 60.]], dtype=float32)>

In [198]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [199]:
# 행렬 곱
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [200]:
K = keras.backend
K.square(K.transpose(t)) + 10

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[11., 26.],
       [14., 35.],
       [19., 46.]], dtype=float32)>

In [201]:
import numpy as np

a = np.array([2., 4, 5])
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 5.])>

In [202]:
t.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [203]:
np.array(t)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [204]:
tf.square(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 4., 16., 25.])>

In [205]:
np.square(t)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

In [206]:
try:
    tf.constant(2.0) + tf.constant(40)
except tf.errors.InvalidArgumentError as ex:
    print(ex)

cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2]


In [207]:
try:
    tf.constant(2.0) + tf.constant(40., dtype=tf.float64)
except tf.errors.InvalidArgumentError as ex:
    print(ex)

cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2]


In [208]:
try:
    tf.constant(2.0) + tf.constant(40.)
except tf.errors.InvalidArgumentError as ex:
    print(ex)

In [209]:
t2 = tf.constant(40., dtype=tf.float64)
tf.constant(2.0) + tf.cast(t2, tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

In [210]:
tf.constant("hello")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello'>

In [211]:
tf.constant("café")

<tf.Tensor: shape=(), dtype=string, numpy=b'caf\xc3\xa9'>

In [212]:
tf.constant("\xa9")

<tf.Tensor: shape=(), dtype=string, numpy=b'\xc2\xa9'>

In [213]:
u = tf.constant([ord(c) for c in "café"])
u

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 99,  97, 102, 233])>

In [214]:
b = tf.strings.unicode_encode(u, "UTF-8")
tf.strings.length(b, unit="UTF8_CHAR")

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [215]:
tf.strings.unicode_decode(b, "UTF-8")

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 99,  97, 102, 233])>

In [216]:
p = tf.constant(["Café", "Coffee", "caffè", "咖啡"])

In [217]:
tf.strings.length(p, unit="UTF8_CHAR")

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 6, 5, 2])>

In [218]:
r = tf.strings.unicode_decode(p, "UTF8")
r

<tf.RaggedTensor [[67, 97, 102, 233], [67, 111, 102, 102, 101, 101],
 [99, 97, 102, 102, 232], [21654, 21857]]>

In [219]:
r[1]

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 67, 111, 102, 102, 101, 101])>

In [220]:
r[1:3]

<tf.RaggedTensor [[67, 111, 102, 102, 101, 101], [99, 97, 102, 102, 232]]>

In [221]:
r2 = tf.ragged.constant([[65, 66], [], [67]])
tf.concat([r, r2], axis=0)

<tf.RaggedTensor [[67, 97, 102, 233], [67, 111, 102, 102, 101, 101],
 [99, 97, 102, 102, 232], [21654, 21857], [65, 66], [], [67]]>

In [222]:
r3 = tf.ragged.constant([[68, 69, 70], [71], [], [72, 73]])
tf.concat([r, r3], axis=1)

<tf.RaggedTensor [[67, 97, 102, 233, 68, 69, 70], [67, 111, 102, 102, 101, 101, 71],
 [99, 97, 102, 102, 232], [21654, 21857, 72, 73]]>

In [223]:
tf.strings.unicode_encode(r3, "UTF-8")

<tf.Tensor: shape=(4,), dtype=string, numpy=array([b'DEF', b'G', b'', b'HI'], dtype=object)>

In [224]:
r.to_tensor()

<tf.Tensor: shape=(4, 6), dtype=int32, numpy=
array([[   67,    97,   102,   233,     0,     0],
       [   67,   111,   102,   102,   101,   101],
       [   99,    97,   102,   102,   232,     0],
       [21654, 21857,     0,     0,     0,     0]])>

In [225]:
s = tf.SparseTensor(indices=[[0,1], [1,0], [2,3]], values=[1., 2, 3], dense_shape=[3, 4])
print(s)

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


In [226]:
tf.sparse.to_dense(s)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [2., 0., 0., 0.],
       [0., 0., 0., 3.]], dtype=float32)>

In [227]:
s2 = s*2
print(s2)

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([2. 4. 6.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


In [228]:
try:
    s3 = s + 1.
except TypeError as ex:
    print(ex)

unsupported operand type(s) for +: 'SparseTensor' and 'float'


In [229]:
s4 = tf.constant([[10., 20.], [30., 40.], [50., 60.], [70., 80.]])
tf.sparse.sparse_dense_matmul(s, s4)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 30.,  40.],
       [ 20.,  40.],
       [210., 240.]], dtype=float32)>

In [230]:
s5 = tf.SparseTensor(indices=[[0, 2], [0, 1]], values=[1., 2.], dense_shape=[3, 4])
print(s5)

SparseTensor(indices=tf.Tensor(
[[0 2]
 [0 1]], shape=(2, 2), dtype=int64), values=tf.Tensor([1. 2.], shape=(2,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


In [231]:
try:
    tf.sparse.to_dense(s5)
except tf.errors.InvalidArgumentError as ex:
    print(ex)

indices[1] = [0,1] is out of order. Many sparse ops require sorted indices.
    Use `tf.sparse.reorder` to create a correctly ordered copy.

 [Op:SparseToDense]


In [232]:
s6 = tf.sparse.reorder(s5)
tf.sparse.to_dense(s6)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 2., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [233]:
set1 = tf.constant([[2, 3, 5, 7], [7, 9, 1, 1]])
set2 = tf.constant([[4, 5, 6], [9, 10, 1]])
tf.sparse.to_dense(tf.sets.union(set1, set2))

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 2,  3,  4,  5,  6,  7],
       [ 1,  7,  9, 10,  0,  0]])>

In [234]:
tf.sparse.to_dense(tf.sets.difference(set1, set2))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 7],
       [7, 0, 0]])>

In [235]:
tf.sparse.to_dense(tf.sets.intersection(set1, set2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 0],
       [1, 9]])>

In [236]:
v = tf.Variable([[1., 2, 3], [4, 5, 6]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [237]:
v.assign(v*2)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [238]:
v[0, 1].assign(42)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 42.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [239]:
v[:, 2].assign([0., 1])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 42.,  0.],
       [ 8., 10.,  1.]], dtype=float32)>

In [240]:
try:
    v[1] = [7., 8., 9.]
except TypeError as ex:
    print(ex)

'ResourceVariable' object does not support item assignment


In [241]:
v.scatter_nd_update(indices=[[0, 0], [1, 2]], updates=[100., 200.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100.,  42.,   0.],
       [  8.,  10., 200.]], dtype=float32)>

In [242]:
sparse_delta = tf.IndexedSlices(values=[[1., 2., 3.], [4., 5., 6.]], indices=[1, 0])
v.scatter_update(sparse_delta)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[4., 5., 6.],
       [1., 2., 3.]], dtype=float32)>

In [243]:
array = tf.TensorArray(dtype=tf.float32, size=3)
array = array.write(0, tf.constant([1., 2.]))
array = array.write(1, tf.constant([3., 10.]))
array = array.write(2, tf.constant([5., 7.]))

In [244]:
array.read(1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 3., 10.], dtype=float32)>

In [245]:
array.stack()

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [0., 0.],
       [5., 7.]], dtype=float32)>

In [246]:
mean, variance = tf.nn.moments(array.stack(), axes=0)
mean

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [247]:
variance

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.6666665, 8.666667 ], dtype=float32)>

In [248]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

housing = fetch_california_housing()
X_train_full, X_test, y_train_full, y_test = train_test_split(
    housing.data, housing.target.reshape(-1, 1), random_state=42)
X_train, X_valid, y_train, y_valid = train_test_split(
    X_train_full, y_train_full, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_valid_scaled = scaler.transform(X_valid)
X_test_scaled = scaler.transform(X_test)

In [249]:
def huber_fn(y_true, y_pred):
    error = y_true - y_pred
    is_small_error = tf.abs(error) < 1
    squared_loss = tf.square(error) / 2
    linear_loss = tf.abs(error) - 0.5
    return tf.where(is_small_error, squared_loss, linear_loss)

In [250]:
model = keras.models.Sequential([
    keras.layers.Dense(30, activation="selu", kernel_initializer="lecun_normal", input_shape=X_train.shape[1:]),
    keras.layers.Dense(1),
])

model.compile(loss=huber_fn, optimizer=keras.optimizers.Nadam(), metrics=["mae"])

model.fit(X_train_scaled, y_train, epochs=2, validation_data=(X_valid_scaled, y_valid))

Epoch 1/2
363/363 [==============================] - 1s 1ms/step - loss: 0.5836 - mae: 0.9389 - val_loss: 0.2799 - val_mae: 0.5713
Epoch 2/2
363/363 [==============================] - 0s 937us/step - loss: 0.2115 - mae: 0.5057 - val_loss: 0.2147 - val_mae: 0.4979


In [251]:
def create_huber(threshold=1.0):
    def huber_fn(y_true, y_pred):
        error = y_true - y_pred
        is_small_error = tf.abs(error) < threshold
        squared_loss = tf.square(error) / 2
        linear_loss  = threshold * tf.abs(error) - threshold**2 / 2
        return tf.where(is_small_error, squared_loss, linear_loss)
    return huber_fn

In [252]:
model.compile(loss=create_huber(2.0), optimizer="nadam", metrics=["mae"])

model.fit(X_train_scaled, y_train, epochs=2, validation_data=(X_valid_scaled, y_valid))

Epoch 1/2
363/363 [==============================] - 1s 1ms/step - loss: 0.2290 - mae: 0.4957 - val_loss: 0.2213 - val_mae: 0.4844
Epoch 2/2
363/363 [==============================] - 0s 948us/step - loss: 0.2187 - mae: 0.4861 - val_loss: 0.2277 - val_mae: 0.4732


In [253]:
model.save("my_model_with_a_custom_loss_threshold_2.h5")

In [254]:
model = keras.models.load_model("my_model_with_a_custom_loss_threshold_2.h5", custom_objects={"huber_fn": create_huber(2.0)})

In [255]:
model.fit(X_train_scaled, y_train, epochs=2, validation_data=(X_valid_scaled, y_valid))

Epoch 1/2
363/363 [==============================] - 1s 1ms/step - loss: 0.2132 - mae: 0.4790 - val_loss: 0.2026 - val_mae: 0.4694
Epoch 2/2
363/363 [==============================] - 0s 975us/step - loss: 0.2092 - mae: 0.4731 - val_loss: 0.2307 - val_mae: 0.4709


In [256]:
class HuberLoss(keras.losses.Loss):
    def __init__(self, threshold=1.0, **kwargs):
        self.threshold = threshold
        super().__init__(**kwargs)
    def call(self, y_true, y_pred):
        error = y_true - y_pred
        is_small_error = tf.abs(error) < self.threshold
        squared_loss = tf.square(error) / 2
        linear_loss = self.threshold * tf.abs(error) - self.threshold**2 / 2
        return tf.where(is_small_error, squared_loss, linear_loss)
    def get_config(self):
        base_config = super().get_config()
        return {**base_config, "threshold": self.threshold}

In [257]:
model = keras.models.Sequential([
    keras.layers.Dense(30, activation="selu", kernel_initializer="lecun_normal", input_shape=X_train.shape[1:]),
    keras.layers.Dense(1),
])

model.compile(loss=HuberLoss(2.), optimizer="nadam", metrics=["mae"])

model.fit(X_train_scaled, y_train, epochs=2, validation_data=(X_valid_scaled, y_valid))

Epoch 1/2
363/363 [==============================] - 1s 1ms/step - loss: 0.7794 - mae: 0.9344 - val_loss: 0.3507 - val_mae: 0.5643
Epoch 2/2
363/363 [==============================] - 0s 990us/step - loss: 0.2422 - mae: 0.5122 - val_loss: 0.2295 - val_mae: 0.4896


In [258]:
model.save("my_model_with_a_custom_loss_class.h5")

In [259]:
model = keras.models.load_model("my_model_with_a_custom_loss_class.h5", custom_objects={"HuberLoss": HuberLoss})

In [260]:
model.fit(X_train_scaled, y_train, epochs=2, validation_data=(X_valid_scaled, y_valid))

Epoch 1/2
363/363 [==============================] - 1s 1ms/step - loss: 0.2277 - mae: 0.4977 - val_loss: 0.2300 - val_mae: 0.4869
Epoch 2/2
363/363 [==============================] - 0s 937us/step - loss: 0.2224 - mae: 0.4892 - val_loss: 0.2033 - val_mae: 0.4678


In [261]:
model.loss.threshold

2.0

In [262]:
keras.backend.clear_session()

In [263]:
def my_softplus(z):
    return tf.math.log(tf.exp(z) + 1.0)

def my_glorot_initializer(shape, dtype=tf.float32):
    stddev = tf.sqrt(2. / (shape[0] + shape[1]))
    return tf.random.normal(shape, stddev=stddev, dtype=dtype)

def my_l1_regularizer(weights):
    return tf.reduce_sum(tf.abs(0.01 * weights))

def my_positive_weights(weights):
    return tf.where(weights < 0., tf.zeros_like(weights), weights)

In [264]:
layer = keras.layers.Dense(
    1,
    activation=my_softplus,
    kernel_initializer=my_glorot_initializer,
    kernel_regularizer=my_l1_regularizer,
    kernel_constraint=my_positive_weights,
)

In [265]:
model = keras.models.Sequential([
    keras.layers.Dense(30, activation="selu", kernel_initializer="lecun_normal"),
    layer,
])

model.compile(loss="mse", optimizer="nadam", metrics=["mae"])

model.fit(X_train_scaled, y_train, epochs=2, validation_data=(X_valid_scaled, y_valid))

Epoch 1/2
363/363 [==============================] - 1s 1ms/step - loss: 1.8377 - mae: 0.9250 - val_loss: 2.8066 - val_mae: 0.5807
Epoch 2/2
363/363 [==============================] - 0s 939us/step - loss: 0.6771 - mae: 0.5361 - val_loss: 1.8812 - val_mae: 0.5275


In [266]:
model.save("my_model_with_many_custom_parts.h5")

In [267]:
model = keras.models.load_model(
    "my_model_with_many_custom_parts.h5",
    custom_objects={
       "my_softplus": my_softplus,
       "my_glorot_initializer": my_glorot_initializer,
       "my_l1_regularizer": my_l1_regularizer,
       "my_positive_weights": my_positive_weights,
    }
)

In [268]:
class MyL1Regularizer(keras.regularizers.Regularizer):
    def __init__(self, factor):
        self.factor = factor
    def __call__(self, weights):
        return tf.reduce_sum(tf.abs(self.factor * weights))
    def get_config(self):
        return {"factor": self.factor}

In [269]:
model = keras.models.Sequential([
    keras.layers.Dense(30, activation="selu", kernel_initializer="lecun_normal", input_shape=X_train.shape[1:]),
    keras.layers.Dense(
        1, 
        activation=my_softplus,
        kernel_initializer=my_glorot_initializer,
        kernel_regularizer=MyL1Regularizer(0.01),
        kernel_constraint=my_positive_weights,
    )
])

model.compile(loss="mse", optimizer="nadam", metrics=["mae"])

model.fit(X_train_scaled, y_train, epochs=2, validation_data=(X_valid_scaled, y_valid))

Epoch 1/2
363/363 [==============================] - 1s 1ms/step - loss: 2.7674 - mae: 1.0265 - val_loss: inf - val_mae: inf
Epoch 2/2
363/363 [==============================] - 0s 1ms/step - loss: 1.1299 - mae: 0.5481 - val_loss: inf - val_mae: inf


In [270]:
model.save("my_model_with_many_custom_parts.h5")

In [271]:
model = keras.models.load_model(
    "my_model_with_many_custom_parts.h5",
    custom_objects={
       "my_softplus": my_softplus,
       "my_glorot_initializer": my_glorot_initializer,
       "MyL1Regularizer": MyL1Regularizer,
       "my_positive_weights": my_positive_weights,
    }
)

In [272]:
keras.backend.clear_session()

In [273]:
model = keras.models.Sequential([
    keras.layers.Dense(30, activation="selu", kernel_initializer="lecun_normal", input_shape=X_train.shape[1:]),
    keras.layers.Dense(1),
])

model.compile(loss="mse", optimizer="nadam", metrics=[create_huber(2.0)])

model.fit(X_train_scaled, y_train, epochs=2)

Epoch 1/2
363/363 [==============================] - 1s 812us/step - loss: 2.2509 - huber_fn: 0.9423
Epoch 2/2
363/363 [==============================] - 0s 713us/step - loss: 0.5595 - huber_fn: 0.2588


In [274]:
precision = keras.metrics.Precision()
precision([0,1,1,1,0,1,0,1], [1,1,0,1,0,1,0,1])

<tf.Tensor: shape=(), dtype=float32, numpy=0.8>

In [275]:
precision([0,1,0,0,1,0,1,1], [1,0,1,1,0,0,0,0])

<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

In [276]:
precision.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

In [277]:
precision.variables

[<tf.Variable 'true_positives:0' shape=(1,) dtype=float32, numpy=array([4.], dtype=float32)>,
 <tf.Variable 'false_positives:0' shape=(1,) dtype=float32, numpy=array([4.], dtype=float32)>]

In [278]:
precision.reset_states()

In [279]:
class HuberMetric(keras.metrics.Metric):
    def __init__(self, threshold=1.0, **kwargs):
        super().__init__(**kwargs)
        self.threshold = threshold
        self.huber_fn = create_huber(threshold)
        self.total = self.add_weight("total", initializer="zeros")
        self.count = self.add_weight("count", initializer="zeros")
    def update_state(self, y_true, y_pred, sample_weight=None):
        metric = self.huber_fn(y_true, y_pred)
        self.total.assign_add(tf.reduce_sum(metric))
        self.count.assign_add(tf.cast(tf.size(y_true), tf.float32))
    def result(self):
        return self.total / self.count
    def get_config(self):
        base_config = super().get_config()
        return {**base_config, "threshold": self.threshold}

In [280]:
m = HuberMetric(2.)
m(tf.constant([2.]), tf.constant([10.]))

<tf.Tensor: shape=(), dtype=float32, numpy=14.0>

In [281]:
m(tf.constant([[0.], [5.]]), tf.constant([[1.], [9.25]]))

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>

In [282]:
m.result()

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>

In [283]:
m.variables

[<tf.Variable 'total:0' shape=() dtype=float32, numpy=21.0>,
 <tf.Variable 'count:0' shape=() dtype=float32, numpy=3.0>]

In [284]:
keras.backend.clear_session()

In [285]:
model = keras.models.Sequential([
    keras.layers.Dense(30, activation="selu", kernel_initializer="lecun_normal", input_shape=X_train.shape[1:]),
    keras.layers.Dense(1),
])

model.compile(loss=create_huber(2.0), optimizer="nadam", metrics=[HuberMetric(2.0)])

model.fit(X_train_scaled.astype(np.float32), y_train.astype(np.float32), epochs=2)

Epoch 1/2
363/363 [==============================] - 1s 765us/step - loss: 0.7309 - huber_metric: 0.7309
Epoch 2/2
363/363 [==============================] - 0s 718us/step - loss: 0.2392 - huber_metric: 0.2392


In [286]:
model.save("my_model_with_a_custom_metric.h5")

In [287]:
model = keras.models.load_model(
    "my_model_with_a_custom_metric.h5",
    custom_objects={
        "huber_fn": create_huber(2.0),
        "HuberMetric": HuberMetric
    }
)

model.fit(X_train_scaled.astype(np.float32), y_train.astype(np.float32), epochs=2)

Epoch 1/2
363/363 [==============================] - 1s 749us/step - loss: 0.2261 - huber_metric: 0.2261
Epoch 2/2
363/363 [==============================] - 0s 713us/step - loss: 0.2219 - huber_metric: 0.2219


In [288]:
model.metrics[-1].threshold

2.0

In [289]:
class HuberMetric(keras.metrics.Mean):
    def __init__(self, threshold=1.0, name='HuberMetric', dtype=None):
        self.threshold = threshold
        self.huber_fn = create_huber(threshold)
        super().__init__(name=name, dtype=dtype)
    def update_state(self, y_true, y_pred, sample_weight=None):
        metric = self.huber_fn(y_true, y_pred)
        super(HuberMetric, self).update_state(metric, sample_weight)
    def get_config(self):
        base_config = super().get_config()
        return {**base_config, "threshold": self.threshold}

In [290]:
keras.backend.clear_session()

In [291]:
model = keras.models.Sequential([
    keras.layers.Dense(30, activation="selu", kernel_initializer="lecun_normal", input_shape=X_train.shape[1:]),
    keras.layers.Dense(1),
])

model.compile(loss=keras.losses.Huber(2.0), optimizer="nadam", weighted_metrics=[HuberMetric(2.0)])

model.fit(X_train_scaled.astype(np.float32), y_train.astype(np.float32), epochs=2, sample_weight=np.random.rand(len(y_train)))

Epoch 1/2
363/363 [==============================] - 1s 793us/step - loss: 0.4209 - HuberMetric: 0.8431
Epoch 2/2
363/363 [==============================] - 0s 763us/step - loss: 0.1282 - HuberMetric: 0.2568


In [292]:
model.save("my_model_with_a_custom_metric_v2.h5")

In [293]:
model = keras.models.load_model("my_model_with_a_custom_metric_v2.h5", custom_objects={"HuberMetric": HuberMetric})

model.fit(X_train_scaled.astype(np.float32), y_train.astype(np.float32), epochs=2)

Epoch 1/2
363/363 [==============================] - 1s 740us/step - loss: 0.2333 - HuberMetric: 0.2333
Epoch 2/2
363/363 [==============================] - 0s 740us/step - loss: 0.2221 - HuberMetric: 0.2221


In [294]:
model.metrics[-1].threshold

2.0

In [295]:
exponential_layer = keras.layers.Lambda(lambda x: tf.exp(x))
exponential_layer([-1., 0., 1.])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.36787945, 1.        , 2.7182817 ], dtype=float32)>

In [296]:
keras.backend.clear_session()

In [297]:
model = keras.models.Sequential([
    keras.layers.Dense(30, activation="relu", input_shape=X_train.shape[1:]),
    keras.layers.Dense(1),
    exponential_layer
])

model.compile(loss="mse", optimizer="sgd")

model.fit(X_train_scaled, y_train, epochs=5, validation_data=(X_valid_scaled, y_valid))

model.evaluate(X_test_scaled, y_test)

Epoch 1/5
363/363 [==============================] - 1s 997us/step - loss: 3.7245 - val_loss: 5.2369
Epoch 2/5
363/363 [==============================] - 0s 807us/step - loss: 4.7270 - val_loss: 2.4452
Epoch 3/5
363/363 [==============================] - 0s 801us/step - loss: 1.7515 - val_loss: 1.1462
Epoch 4/5
363/363 [==============================] - 0s 934us/step - loss: 0.9472 - val_loss: 0.7199
Epoch 5/5
162/162 [==============================] - 0s 590us/step - loss: 0.6545


0.6544619798660278

In [298]:
class MyDense(keras.layers.Layer):
    def __init__(self, units, activation=None, **kwargs):
        super().__init__(**kwargs)
        self.units = units
        self.activation = keras.activations.get(activation)
        
    def build(self, batch_input_shape):
        self.kernel = self.add_weight(
            name="kernel",
            shape=[batch_input_shape[-1], self.units],
            initializer="glorot_normal"
        )
        self.bias = self.add_weight(
            name="bias",
            shape=[self.units],
            initializer="zeros"
        )
        super().build(batch_input_shape)

    def call(self, X):
        return self.activation(X @ self.kernel + self.bias)
    
    def compute_output_shape(self, batch_input_shape):
        return tf.TensorShape(batch_input_shape.as_list()[:-1] + [self.units])
    
    def get_config(self):
        base_config = super().get_config()
        return {**base_config, "units": self.units, "activation": keras.activations.serialize(self.activation)}

In [299]:
keras.backend.clear_session()

In [300]:
model = keras.models.Sequential([
    MyDense(30, activation="relu", input_shape=X_train.shape[1:]),
    MyDense(1),
])

model.compile(loss="mse", optimizer="nadam")

model.fit(X_train_scaled, y_train, epochs=2, validation_data=(X_valid_scaled, y_valid))

model.evaluate(X_test_scaled, y_test)

Epoch 1/2
363/363 [==============================] - 1s 1ms/step - loss: 2.4850 - val_loss: 0.8010
Epoch 2/2
162/162 [==============================] - 0s 557us/step - loss: 0.5083


0.5083198547363281

In [301]:
model.save("./models/my_model_with_a_custom_layer.h5")

In [303]:
model = keras.models.load_model("./models/my_model_with_a_custom_layer.h5", custom_objects={"MyDense": MyDense})

In [304]:
class MyMultiLayer(keras.layers.Layer):
    def call(self, X):
        X1, X2 = X
        return X1 + X2, X1 * X2
    
    def compute_output_shape(self, batch_input_shape):
        b1, b2 = batch_input_shape
        return b1, b2

In [305]:
def split_data(data):
    columns_count = data.shape[-1]
    half = columns_count // 2
    return data[:, :half], data[:, half:]

X_train_scaled_A, X_train_scaled_B = split_data(X_train_scaled)
X_valid_scaled_A, X_valid_scaled_B = split_data(X_valid_scaled)
X_test_scaled_A, X_test_scaled_B = split_data(X_test_scaled)

X_train_scaled_A.shape, X_train_scaled_B.shape

((11610, 4), (11610, 4))

In [306]:
MyMultiLayer()((X_train_scaled_A, X_train_scaled_B))

(<tf.Tensor: shape=(11610, 4), dtype=float32, numpy=
 array([[-0.17324547, -1.6507294 , -0.01412493, -1.4073021 ],
        [ 2.6134481 , -1.6637297 , -0.5110694 ,  0.86339283],
        [-0.5025582 , -0.27013135,  2.1268167 , -0.6402433 ],
        ...,
        [-0.7709261 ,  0.6388412 , -1.2357894 ,  1.4055338 ],
        [-0.9933209 ,  1.8356445 ,  0.41289914, -0.16435926],
        [ 0.7240328 ,  0.00968345,  1.4208122 , -1.4639156 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(11610, 4), dtype=float32, numpy=
 array([[-0.00402183,  0.61749667, -0.8766508 , -0.02112347],
        [ 1.3997903 , -0.38343248, -0.37163973, -0.2558276 ],
        [ 0.03643769, -0.00890543,  1.0706553 , -1.7933904 ],
        ...,
        [-0.5534281 ,  0.0678305 ,  0.371412  ,  0.29685235],
        [ 0.05403009, -0.02504723, -0.0567511 ,  0.0063295 ],
        [-0.15393297, -0.03349337,  0.3358127 ,  0.2048483 ]],
       dtype=float32)>)

In [307]:
class AddGaussianNoise(keras.layers.Layer):
    def __init__(self, stddev, **kwargs):
        super().__init__(**kwargs)
        self.stddev = stddev

    def call(self, X, training=None):
        if training:
            noise = tf.random.normal(tf.shape(X), stddev=self.stddev)
            return X + noise
        else:
            return X

    def compute_output_shape(self, batch_input_shape):
        return batch_input_shape

In [308]:
keras.backend.clear_session()

In [309]:
model = keras.models.Sequential([
    AddGaussianNoise(stddev=1.0),
    keras.layers.Dense(30, activation="selu"),
    keras.layers.Dense(1)
])

model.compile(loss="mse", optimizer="nadam")

model.fit(X_train_scaled, y_train, epochs=2, validation_data=(X_valid_scaled, y_valid))

model.evaluate(X_test_scaled, y_test)

Epoch 1/2
363/363 [==============================] - 1s 1ms/step - loss: 2.3593 - val_loss: 0.8691
Epoch 2/2
162/162 [==============================] - 0s 609us/step - loss: 0.8132


0.8131663799285889

In [324]:
class ResidualBlock(keras.layers.Layer):
    def __init__(self, n_layers, n_neurons, **kwargs):
        super().__init__(**kwargs)
        self.hidden = [keras.layers.Dense(n_neurons, activation="elu", kernel_initializer="he_normal") for _ in range(n_layers)]

    def call(self, inputs):
        Z = inputs
        for layer in self.hidden:
            Z = layer(Z)
        return inputs + Z

In [327]:
class ResidualRegressor(keras.models.Model):
    def __init__(self, output_dim, **kwargs):
        super().__init__(**kwargs)
        self.hidden1 = keras.layers.Dense(30, activation="elu", kernel_initializer="he_normal")
        self.block1 = ResidualBlock(2, 30)
        self.block2 = ResidualBlock(2, 30)
        self.out = keras.layers.Dense(output_dim)

    def call(self, inputs):
        Z = self.hidden1(inputs)
        for _ in range(1+3):
            Z = self.block1(Z)
        Z = self.block2(Z)
        return self.out(Z)

In [328]:
keras.backend.clear_session()

In [329]:
model = ResidualRegressor(1)

model.compile(loss="mse", optimizer="nadam")

model.fit(X_train_scaled, y_train, epochs=5)

model.evaluate(X_test_scaled, y_test)

model.predict(X_test_scaled)

Epoch 1/5
363/363 [==============================] - 1s 1ms/step - loss: 3.4686
Epoch 2/5
363/363 [==============================] - 0s 1ms/step - loss: 1.5977
Epoch 3/5
363/363 [==============================] - 0s 1ms/step - loss: 1.0274
Epoch 4/5
363/363 [==============================] - 0s 1ms/step - loss: 0.5973
Epoch 5/5
162/162 [==============================] - 0s 770us/step - loss: 0.4754


array([[0.4503222],
       [1.8442676],
       [3.570568 ],
       ...,
       [1.5346203],
       [2.3036103],
       [4.2730083]], dtype=float32)

In [330]:
model.save("./models/my_custom_model.ckpt")

INFO:tensorflow:Assets written to: ./models/my_custom_model.ckpt\assets


INFO:tensorflow:Assets written to: ./models/my_custom_model.ckpt\assets


In [331]:
model = keras.models.load_model("./models/my_custom_model.ckpt")

In [332]:
model.fit(X_train_scaled, y_train, epochs=5)

Epoch 1/5
363/363 [==============================] - 2s 1ms/step - loss: 0.5604
Epoch 2/5
363/363 [==============================] - 0s 1ms/step - loss: 0.5270
Epoch 3/5
363/363 [==============================] - 0s 1ms/step - loss: 0.3874
Epoch 4/5
363/363 [==============================] - 0s 1ms/step - loss: 0.8462
Epoch 5/5
363/363 [==============================] - 0s 1ms/step - loss: 0.4039


In [333]:
keras.backend.clear_session()

In [336]:
block1 = ResidualBlock(2, 30)

model = keras.models.Sequential([
    keras.layers.Dense(30, activation="elu", kernel_initializer="he_normal"),
    block1, block1, block1, block1, block1,
    keras.layers.Dense(1),
])

model.compile(loss="mse", optimizer="nadam")

model.fit(X_train_scaled, y_train, epochs=5)

model.evaluate(X_test_scaled, y_test)

model.predict(X_test_scaled)

Epoch 1/5
363/363 [==============================] - 1s 898us/step - loss: 1.2512
Epoch 2/5
363/363 [==============================] - 0s 906us/step - loss: 0.4634
Epoch 3/5
363/363 [==============================] - 0s 928us/step - loss: 0.4214
Epoch 4/5
363/363 [==============================] - 0s 1ms/step - loss: 0.5095
Epoch 5/5
162/162 [==============================] - 0s 634us/step - loss: 0.5247


array([[0.6550993],
       [1.7828933],
       [3.478369 ],
       ...,
       [1.6039333],
       [2.6736116],
       [3.7114036]], dtype=float32)

In [349]:
class ReconstructingRegressor(keras.Model):
    def __init__(self, output_dim, **kwargs):
        super().__init__(**kwargs)
        self.hidden = [keras.layers.Dense(30, activation="selu", kernel_initializer="lecun_normal") for _ in range(5)]
        self.out = keras.layers.Dense(output_dim)
        self.reconstruction_mean = keras.metrics.Mean(name="reconstruction_error")

    def build(self, batch_input_shape):
        n_inputs = batch_input_shape[-1]
        self.reconstruct = keras.layers.Dense(n_inputs)

    def call(self, inputs, training=None):
        Z = inputs
        for layer in self.hidden:
            Z = layer(Z)
        reconstruction = self.reconstruct(Z)
        self.recon_loss = 0.05 * tf.reduce_mean(tf.square(reconstruction - inputs))
        
        if training:
            result = self.reconstruction_mean(recon_loss)
            self.add_metric(result)
        return self.out(Z)
    
    def train_step(self, data):
        x, y = data

        with tf.GradientTape() as tape:
            y_pred = self(x)
            loss = self.compiled_loss(y, y_pred, regularization_losses=[self.recon_loss])

        gradients = tape.gradient(loss, self.trainable_variables)
        self.optimizer.apply_gradients(zip(gradients, self.trainable_variables))

        return {m.name: m.result() for m in self.metrics}

In [350]:
keras.backend.clear_session()

In [351]:
model = ReconstructingRegressor(1)
model.compile(loss="mse", optimizer="nadam")
model.fit(X_train_scaled, y_train, epochs=2)
model.predict(X_test_scaled)

Epoch 1/2
363/363 [==============================] - 1s 975us/step - loss: 0.7463 - reconstruction_error: 0.0000e+00
Epoch 2/2
363/363 [==============================] - 0s 962us/step - loss: 0.4250 - reconstruction_error: 0.0000e+00


array([[0.6786929],
       [1.6579387],
       [3.5541344],
       ...,
       [1.3917664],
       [3.299142 ],
       [3.91603  ]], dtype=float32)