In [2]:
import tensorflow as tf
from tensorflow import keras

In [91]:
n_step = 5
dataset = tf.data.Dataset.from_tensor_slices(tf.range(15))
dataset = dataset.window(n_step, shift=2, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.shuffle(10).map(lambda window: (window[:-1], window[1:]))
dataset = dataset.batch(3).prefetch(1)

for a in dataset:
    print(a)

(<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 2,  3,  4,  5],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])>, <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 3,  4,  5,  6],
       [ 9, 10, 11, 12],
       [11, 12, 13, 14]])>)
(<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[6, 7, 8, 9],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])>, <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 7,  8,  9, 10],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])>)


In [92]:
shakespeare_url = "https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt"
filepath = keras.utils.get_file("shakespeare.txt", shakespeare_url)
with open(filepath) as f:
    shakespeare_text = f.read()

1130496/1115394 [==============================] - 0s 0us/step


In [99]:
print(shakespeare_text[:60])

First Citizen:
Before we proceed any further, hear me speak.


In [100]:
tokenizer = keras.preprocessing.text.Tokenizer(char_level=True)
tokenizer.fit_on_texts(shakespeare_text)

In [102]:
tokenizer.texts_to_sequences(["abcABCdD"])

[[5, 22, 19, 5, 22, 19, 13, 13]]

In [104]:
tokenizer.sequences_to_texts([[5,5,5,5,5,5,13,13]])

['a a a a a a d d']

In [105]:
max_id = len(tokenizer.word_index)
dataset_size = tokenizer.document_count

In [108]:
import numpy as np


[encoded] = np.array(tokenizer.texts_to_sequences([shakespeare_text])) - 1

In [111]:
train_size = dataset_size * 90 // 100
dataset = tf.data.Dataset.from_tensor_slices(encoded[:train_size])

In [118]:
n_step = 100
window_length = n_step + 1
dataset = dataset.window(window_length, shift=1, drop_remainder=True)